#!/usr/bin/env python3
"""
The Daybook — a "learn one thing a day" Telegram bot.

Each morning it pushes you a fresh flashcard on a subject you're studying,
generated by the Google Gemini API. Older cards resurface on a widening
spaced-repetition schedule (SM-2). You can also review or quiz on demand.

Setup (see the README notes in chat):
  pip install -r requirements.txt
  export TELEGRAM_BOT_TOKEN="123:ABC..."     # from @BotFather
  export GEMINI_API_KEY="AIza..."            # from aistudio.google.com/apikey
  export DAYBOOK_TZ="Asia/Tokyo"             # optional, defaults to UTC
  python daybook_bot.py
"""

import os, sqlite3, time, json, random, asyncio, logging, threading, datetime as dt
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from zoneinfo import ZoneInfo
import requests
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.constants import ParseMode
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler, MessageHandler,
    ContextTypes, filters,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("daybook")

MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
TZ    = ZoneInfo(os.getenv("DAYBOOK_TZ", "UTC"))
DB    = os.getenv("DAYBOOK_DB", "daybook.db")
DAY   = 86400.0

# Published free-tier ceiling for gemini-2.5-flash (requests/day). Used only
# to show a "X / LIMIT" progress bar in /usage — Google does not expose a
# live remaining-quota endpoint, so this is a local counter against a
# constant. Override if your tier differs or Google changes the number.
FREE_RPD_LIMIT = int(os.getenv("GEMINI_FREE_RPD", "1500"))

PRESETS = [
    {"name": "Japanese words", "topic": "Japanese vocabulary", "level": "beginner",     "kind": "vocab", "lang": "Japanese"},
    {"name": "French words",   "topic": "French vocabulary",   "level": "beginner",     "kind": "vocab", "lang": "French"},
    {"name": "Finance terms",  "topic": "personal finance & investing", "level": "intermediate", "kind": "term"},
    {"name": "Python concepts","topic": "Python programming concepts",  "level": "intermediate", "kind": "concept"},
    {"name": "Big ideas",      "topic": "foundational ideas across science, history & philosophy", "level": "curious", "kind": "concept"},
    {"name": "GARP RAI",       "topic": "the GARP Risk and AI (RAI) certificate curriculum — AI/ML fundamentals, "
                                          "AI risk factors, model risk, governance frameworks (e.g. NIST AI RMF), "
                                          "and responsible/ethical AI in financial risk management",
     "level": "advanced", "kind": "lesson", "syllabus_key": "garp_rai"},
    {"name": "Stocks & investing", "topic": "equity investing — financial statement analysis, valuation methods "
                                             "(DCF, multiples), market mechanics, portfolio theory, and key ratios",
     "level": "intermediate", "kind": "lesson", "syllabus_key": "stocks"},
]

# Ordered topic lists for "lesson" decks that follow a real curriculum, so
# daily cards march through the material in order rather than being picked
# freely by the model. Loosely follows GARP's published RAI module structure
# (AI & Risk Intro -> AI Tools & Techniques -> Risk Factors -> Responsible &
# Ethical AI -> Data & AI Model Governance; the optional Case Studies module
# is left out since it's untested / 0% exam weight) and a standard equity-
# investing study sequence for Stocks & investing.
SYLLABI = {
    "garp_rai": [
        # Module 1 — AI and Risk: Introduction & Overview
        "History and evolution of AI and machine learning",
        "Core AI/ML paradigms: supervised, unsupervised, and reinforcement learning",
        "How large language models and generative AI work",
        "Overview of AI-specific risk categories for organizations",
        # Module 2 — AI Tools and Techniques
        "Regression models and their use in business decision-making",
        "Classification models: decision trees and logistic regression",
        "Clustering and segmentation techniques",
        "Neural networks and deep learning fundamentals",
        "Natural language processing techniques",
        "Time series forecasting with AI/ML",
        "Model evaluation metrics: accuracy, precision, recall, AUC",
        "Feature engineering and data preprocessing",
        "Ensemble methods: random forests and boosting",
        "Explainability and interpretability techniques (SHAP, LIME)",
        # Module 3 — Risks and Risk Factors
        "Model risk: overfitting, underfitting, and model drift",
        "Data quality and bias risk in AI systems",
        "AI-specific cybersecurity risks: adversarial attacks and data poisoning",
        "Third-party and vendor risk in AI systems",
        "Operational and concentration risk from AI adoption",
        "Systemic risk implications of widespread AI use in finance",
        # Module 4 — Responsible and Ethical AI
        "AI ethics principles: fairness, accountability, and transparency",
        "Algorithmic bias and discrimination in AI systems",
        "Privacy considerations and regulation (e.g. GDPR) for AI",
        "Human oversight and human-in-the-loop design",
        # Module 5 — Data and AI Model Governance
        "AI model governance frameworks and the model lifecycle",
        "Model validation and independent review",
        "The NIST AI Risk Management Framework (AI RMF)",
        "Documentation, change management, and audit trails for AI models",
        "The regulatory landscape for AI in financial services",
    ],
    "stocks": [
        "How stock markets work: exchanges, market makers, and order types",
        "Reading an income statement",
        "Reading a balance sheet",
        "Reading a cash flow statement",
        "Key profitability ratios: ROE, ROA, and margins",
        "Liquidity and solvency ratios: current ratio and debt-to-equity",
        "The price-to-earnings (P/E) ratio: uses and limitations",
        "Other valuation multiples: P/B, EV/EBITDA, and P/S",
        "Discounted cash flow (DCF) valuation basics",
        "Estimating a company's cost of capital (WACC)",
        "The dividend discount model",
        "Growth investing vs. value investing",
        "Market capitalization and float",
        "Diversification and portfolio risk",
        "Modern portfolio theory and the efficient frontier",
        "Beta and systematic vs. unsystematic risk",
        "The Capital Asset Pricing Model (CAPM)",
        "Bond basics and how interest rates affect stock valuations",
        "Reading earnings reports and management guidance",
        "Common behavioral biases in investing",
    ],
}

# ── database ─────────────────────────────────────────────────────────────────
def db():
    c = sqlite3.connect(DB)
    c.row_factory = sqlite3.Row
    return c

def init_db():
    with db() as c:
        c.executescript("""
        CREATE TABLE IF NOT EXISTS users(
            chat_id INTEGER PRIMARY KEY, active_deck INTEGER,
            digest_h INTEGER DEFAULT 8, digest_m INTEGER DEFAULT 0,
            streak INTEGER DEFAULT 0, streak_day TEXT);
        CREATE TABLE IF NOT EXISTS decks(
            id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER,
            name TEXT, topic TEXT, level TEXT, kind TEXT, lang TEXT,
            syllabus_key TEXT, syllabus_idx INTEGER DEFAULT 0);
        CREATE TABLE IF NOT EXISTS cards(
            id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER, deck_id INTEGER,
            front TEXT, back TEXT, example TEXT, hint TEXT, created REAL,
            interval REAL DEFAULT 0, ease REAL DEFAULT 2.5, reps INTEGER DEFAULT 0,
            lapses INTEGER DEFAULT 0, due REAL, last_reviewed REAL);
        CREATE TABLE IF NOT EXISTS newlog(
            chat_id INTEGER, deck_id INTEGER, last_new TEXT,
            PRIMARY KEY(chat_id, deck_id));
        CREATE TABLE IF NOT EXISTS usage(
            day TEXT PRIMARY KEY, requests INTEGER DEFAULT 0,
            prompt_tokens INTEGER DEFAULT 0, output_tokens INTEGER DEFAULT 0,
            total_tokens INTEGER DEFAULT 0);
        """)
        # migrate older DBs that predate the syllabus columns
        cols = {r["name"] for r in c.execute("PRAGMA table_info(decks)").fetchall()}
        if "syllabus_key" not in cols:
            c.execute("ALTER TABLE decks ADD COLUMN syllabus_key TEXT")
        if "syllabus_idx" not in cols:
            c.execute("ALTER TABLE decks ADD COLUMN syllabus_idx INTEGER DEFAULT 0")

def record_usage(prompt_tok, output_tok, total_tok):
    day = today_str()
    with db() as c:
        c.execute("INSERT INTO usage(day,requests,prompt_tokens,output_tokens,total_tokens) "
                  "VALUES(?,1,?,?,?) ON CONFLICT(day) DO UPDATE SET "
                  "requests=requests+1, prompt_tokens=prompt_tokens+?, "
                  "output_tokens=output_tokens+?, total_tokens=total_tokens+?",
                  (day, prompt_tok, output_tok, total_tok, prompt_tok, output_tok, total_tok))

def get_usage(day=None):
    day = day or today_str()
    with db() as c:
        r = c.execute("SELECT * FROM usage WHERE day=?", (day,)).fetchone()
        return r or {"day": day, "requests": 0, "prompt_tokens": 0, "output_tokens": 0, "total_tokens": 0}

def ensure_user(chat_id):
    with db() as c:
        c.execute("INSERT OR IGNORE INTO users(chat_id) VALUES(?)", (chat_id,))

def get_user(chat_id):
    with db() as c:
        return c.execute("SELECT * FROM users WHERE chat_id=?", (chat_id,)).fetchone()

def set_active(chat_id, deck_id):
    with db() as c:
        c.execute("UPDATE users SET active_deck=? WHERE chat_id=?", (deck_id, chat_id))

def list_decks(chat_id):
    with db() as c:
        return c.execute("SELECT * FROM decks WHERE chat_id=? ORDER BY id", (chat_id,)).fetchall()

def get_deck(deck_id):
    with db() as c:
        return c.execute("SELECT * FROM decks WHERE id=?", (deck_id,)).fetchone()

def active_deck(chat_id):
    u = get_user(chat_id)
    if not u or not u["active_deck"]:
        return None
    return get_deck(u["active_deck"])

def add_deck(chat_id, d):
    with db() as c:
        cur = c.execute(
            "INSERT INTO decks(chat_id,name,topic,level,kind,lang,syllabus_key,syllabus_idx) VALUES(?,?,?,?,?,?,?,0)",
            (chat_id, d["name"], d["topic"], d["level"], d["kind"], d.get("lang"), d.get("syllabus_key")))
        return cur.lastrowid

def syllabus_progress(deck):
    """Return (current_topic_or_None, done_count, total_count) for a deck's syllabus."""
    key = deck["syllabus_key"] if deck else None
    if not key or key not in SYLLABI:
        return None, 0, 0
    topics = SYLLABI[key]
    idx = deck["syllabus_idx"] or 0
    current = topics[idx] if idx < len(topics) else None
    return current, idx, len(topics)

def advance_syllabus(deck_id):
    with db() as c:
        c.execute("UPDATE decks SET syllabus_idx = syllabus_idx + 1 WHERE id=?", (deck_id,))

def deck_cards(chat_id, deck_id):
    with db() as c:
        return c.execute("SELECT * FROM cards WHERE chat_id=? AND deck_id=? ORDER BY id",
                         (chat_id, deck_id)).fetchall()

def due_cards(chat_id, deck_id, now):
    with db() as c:
        return c.execute("SELECT * FROM cards WHERE chat_id=? AND deck_id=? AND due<=? ORDER BY due",
                         (chat_id, deck_id, now)).fetchall()

def get_card(card_id):
    with db() as c:
        return c.execute("SELECT * FROM cards WHERE id=?", (card_id,)).fetchone()

def insert_card(chat_id, deck_id, card, sched, now):
    with db() as c:
        cur = c.execute(
            "INSERT INTO cards(chat_id,deck_id,front,back,example,hint,created,interval,ease,reps,lapses,due,last_reviewed)"
            " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (chat_id, deck_id, card["front"], card["back"], card.get("example",""), card.get("hint",""),
             now, sched["interval"], sched["ease"], sched["reps"], sched["lapses"], sched["due"], now))
        return cur.lastrowid

def update_sched(card_id, s):
    with db() as c:
        c.execute("UPDATE cards SET interval=?,ease=?,reps=?,lapses=?,due=?,last_reviewed=? WHERE id=?",
                  (s["interval"], s["ease"], s["reps"], s["lapses"], s["due"], s["last_reviewed"], card_id))

def mark_new_today(chat_id, deck_id, day):
    with db() as c:
        c.execute("INSERT INTO newlog(chat_id,deck_id,last_new) VALUES(?,?,?) "
                  "ON CONFLICT(chat_id,deck_id) DO UPDATE SET last_new=?", (chat_id, deck_id, day, day))

def got_new_today(chat_id, deck_id, day):
    with db() as c:
        r = c.execute("SELECT last_new FROM newlog WHERE chat_id=? AND deck_id=?", (chat_id, deck_id)).fetchone()
        return bool(r and r["last_new"] == day)

def all_user_ids():
    with db() as c:
        return [r["chat_id"] for r in c.execute("SELECT chat_id FROM users").fetchall()]

# ── time / streak ────────────────────────────────────────────────────────────
def now_ts():
    return time.time()

def today_str():
    return dt.datetime.now(TZ).date().isoformat()

def touch_streak(chat_id):
    u = get_user(chat_id)
    t = today_str()
    if u["streak_day"] == t:
        return u["streak"]
    yest = (dt.datetime.now(TZ).date() - dt.timedelta(days=1)).isoformat()
    new = u["streak"] + 1 if u["streak_day"] == yest else 1
    with db() as c:
        c.execute("UPDATE users SET streak=?, streak_day=? WHERE chat_id=?", (new, t, chat_id))
    return new

# ── spaced repetition (SM-2, lightly tuned) ──────────────────────────────────
def schedule(card, rating, t):
    interval = card["interval"] if card else 0
    ease     = card["ease"] if card else 2.5
    reps     = card["reps"] if card else 0
    lapses   = card["lapses"] if card else 0
    if rating == "again":
        return dict(interval=0, ease=max(1.3, ease-0.2), reps=0, lapses=lapses+1, due=t+60, last_reviewed=t)
    if rating == "hard":
        ease = max(1.3, ease-0.15); interval = 1 if reps == 0 else max(1, round(interval*1.2))
    elif rating == "good":
        interval = 1 if reps == 0 else (3 if reps == 1 else round(interval*ease))
    elif rating == "easy":
        ease += 0.15; interval = 2 if reps == 0 else (4 if reps == 1 else round(interval*ease*1.3))
    return dict(interval=interval, ease=ease, reps=reps+1, lapses=lapses,
                due=t+interval*DAY, last_reviewed=t)

def fmt_days(d):
    if d <= 0: return "now"
    if d < 1:  return f"{round(d*24)}h"
    if d < 30: return f"{round(d)}d"
    if d < 365:return f"{round(d/30)}mo"
    return f"{d/365:.1f}y"

def preview(card, rating):
    return "<10m" if rating == "again" else fmt_days(schedule(card, rating, 0)["interval"])

# ── Gemini ────────────────────────────────────────────────────────────────────
def _gemini_sync(system, user, json_out=True):
    key = os.environ["GEMINI_API_KEY"]
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent"
    body = {
        "system_instruction": {"parts": [{"text": system}]},
        "contents": [{"role": "user", "parts": [{"text": user}]}],
        "generationConfig": ({"responseMimeType": "application/json", "temperature": 0.9}
                             if json_out else {"temperature": 0.9}),
    }
    r = requests.post(url, headers={"Content-Type": "application/json", "x-goog-api-key": key},
                      json=body, timeout=60)
    if r.status_code != 200:
        detail = ""
        try: detail = r.json().get("error", {}).get("message", "")
        except Exception: pass
        if r.status_code == 429:
            raise RuntimeError("Hit the Gemini free-tier rate limit — try again in a minute, or check /usage.")
        if r.status_code in (400, 403):
            raise RuntimeError("Gemini API key was rejected — check GEMINI_API_KEY.")
        raise RuntimeError(f"Gemini error {r.status_code}: {detail}")
    data = r.json()
    usage = data.get("usageMetadata", {})
    record_usage(usage.get("promptTokenCount", 0),
                  usage.get("candidatesTokenCount", 0),
                  usage.get("totalTokenCount", 0))
    parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
    return "".join(p.get("text", "") for p in parts)

async def gemini(system, user, json_out=True):
    return await asyncio.to_thread(_gemini_sync, system, user, json_out)

def parse_json(text):
    t = text.replace("```json", "").replace("```", "").strip()
    a, b = t.find("{"), t.rfind("}")
    return json.loads(t[a:b+1] if a >= 0 else t)

async def gen_card(deck, existing_fronts, syllabus_topic=None, syllabus_done=False):
    avoid = ("Do NOT repeat any of these already-covered items: "
             + "; ".join(existing_fronts[-40:]) + ".") if existing_fronts else ""
    if deck["kind"] == "vocab":
        lang = deck["lang"]
        shape = (f"front = the {lang} word written naturally "
                 f"(for Japanese, give the word in kanji/kana followed by its reading in parentheses; "
                 f"for French, include the gender article such as le/la/un/une), "
                 f"back = English meaning plus part of speech, "
                 f"example = a natural short sentence in {lang} using the word (add a reading/translation if the script isn't Latin), "
                 f"hint = a brief memory aid.")
    elif deck["kind"] == "lesson":
        shape = (f"front = the name of today's concept/topic — use exactly this: '{syllabus_topic}'" if syllabus_topic else
                 "front = the name of the concept/topic for today (specific, not generic — e.g. "
                 "'Value at Risk (VaR)' not 'risk metrics'), ")
        shape += (" back = a thorough explanation in 3-5 short paragraphs (roughly 150-250 words total) covering "
                 "what it is, why it matters, and how it's used or calculated in practice — written like a study "
                 "note for someone preparing for an exam or professional role, "
                 "example = a concrete worked example, case study, or scenario that applies the concept, "
                 "hint = one sentence: the key takeaway or exam tip to remember.")
    else:
        shape = ("front = the term or concept name, back = a clear 1-2 sentence explanation, "
                 "example = a concrete example or tiny code snippet that makes it click, "
                 "hint = a one-line intuition.")
    system = ("You are a precise, encouraging tutor building ONE spaced-repetition flashcard. "
              "Reply with ONLY a JSON object with keys: front, back, example, hint. Keep each field tight.")
    if syllabus_topic:
        user = f"Topic: {deck['topic']}. Level: {deck['level']}. {shape}"
    elif syllabus_done:
        user = (f"Topic: {deck['topic']}. Level: {deck['level']}. The learner has finished the core curriculum "
                f"sequence. Make one genuinely useful bonus/advanced flashcard that reinforces or extends it — "
                f"e.g. a case study, a trickier edge case, or a synthesis across topics. {shape} {avoid}")
    else:
        user = (f"Topic: {deck['topic']}. Level: {deck['level']}. "
                f"Make one genuinely useful, NEW flashcard. {shape} {avoid}")
    return parse_json(await gemini(system, user))

async def grade(card, answer):
    system = ('You grade a learner\'s recall attempt generously but honestly. '
              'Reply with ONLY JSON: {"correct": boolean, "feedback": string}. '
              'Feedback is one warm, specific sentence. If the back-of-card text is a longer '
              'explanation, judge whether the learner captured its core idea, not every detail.')
    user = (f'Prompt shown: "{card["front"]}". Expected answer/explanation: "{card["back"]}". '
            f'The learner wrote: "{answer}". Was it essentially right?')
    return parse_json(await gemini(system, user))

# ── formatting ────────────────────────────────────────────────────────────────
def card_front_md(card, tag=""):
    head = f"<i>{tag}</i>\n" if tag else ""
    hint = f"\n<i>{card['hint']}</i>" if card["hint"] else ""
    return f"{head}<b>{card['front']}</b>{hint}"

def card_back_md(card):
    ex = f"\n\n<code>{card['example']}</code>" if card["example"] else ""
    return f"<b>{card['front']}</b>\n\n{card['back']}{ex}"

def rate_keyboard(card):
    row = [InlineKeyboardButton(f"{r.title()} · {preview(card, r)}", callback_data=f"rate:{card['id']}:{r}")
           for r in ("again", "hard", "good", "easy")]
    return InlineKeyboardMarkup([row[:2], row[2:]])

# ── commands ──────────────────────────────────────────────────────────────────
async def cmd_start(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    chat = update.effective_chat.id
    ensure_user(chat)
    await update.message.reply_text(
        "<b>The Daybook</b> 🌿\nOne thing a day, made to stick.\n\n"
        "Each morning I'll send a fresh card on a subject you're studying, and resurface "
        "older ones right before you'd forget them. Pick a subject to begin:",
        parse_mode=ParseMode.HTML, reply_markup=preset_keyboard())
    await schedule_digest(ctx.application, chat)

def preset_keyboard():
    rows = [[InlineKeyboardButton(p["name"], callback_data=f"preset:{i}")] for i, p in enumerate(PRESETS)]
    rows.append([InlineKeyboardButton("➕ Custom subject", callback_data="newdeck")])
    return InlineKeyboardMarkup(rows)

async def cmd_help(update: Update, ctx):
    await update.message.reply_text(
        "<b>Commands</b>\n"
        "/learn — today's new card\n"
        "/review — go through cards that are due\n"
        "/quiz — get quizzed; type your answer and I'll grade it\n"
        "/deck — switch subject\n"
        "/newdeck — create a custom subject\n"
        "/stats — streak and your memory horizon\n"
        "/syllabus — curriculum progress (for GARP RAI, Stocks, etc.)\n"
        "/usage — today's Gemini request/token count\n"
        "/settime HH:MM — when to send the morning card\n"
        "/cancel — stop the current action",
        parse_mode=ParseMode.HTML)

async def cmd_deck(update: Update, ctx):
    decks = list_decks(update.effective_chat.id)
    if not decks:
        return await update.message.reply_text("No subjects yet. Use /start to pick one.")
    rows = [[InlineKeyboardButton(d["name"], callback_data=f"setdeck:{d['id']}")] for d in decks]
    rows.append([InlineKeyboardButton("➕ Custom subject", callback_data="newdeck")])
    await update.message.reply_text("Switch subject:", reply_markup=InlineKeyboardMarkup(rows))

async def cmd_learn(update: Update, ctx):
    await deliver_new_card(update.effective_chat.id, ctx)

async def deliver_new_card(chat, ctx, prefix=""):
    deck = active_deck(chat)
    bot = ctx.bot
    if not deck:
        return await bot.send_message(chat, "Pick a subject first with /start or /deck.")
    if got_new_today(chat, deck["id"], today_str()):
        prefix = prefix or "Today's seed is already planted — here's one more anyway.\n\n"
    msg = await bot.send_message(chat, prefix + "✦ Drawing a card…")
    topic, done, total = syllabus_progress(deck)
    try:
        existing = [c["front"] for c in deck_cards(chat, deck["id"])]
        data = await gen_card(deck, existing, syllabus_topic=topic,
                              syllabus_done=(total > 0 and topic is None))
    except Exception as e:
        return await msg.edit_text(f"Couldn't draw a card: {e}")
    base = {"interval": 0, "ease": 2.5, "reps": 0, "lapses": 0}
    sched = schedule(base, "good", now_ts())          # first sight → returns tomorrow
    cid = insert_card(chat, deck["id"], data, sched, now_ts())
    mark_new_today(chat, deck["id"], today_str())
    touch_streak(chat)
    if topic is not None:
        advance_syllabus(deck["id"])
        tag = f"Today · {deck['name']} · {done+1}/{total}"
    elif total:
        tag = f"Today · {deck['name']} · bonus (syllabus complete)"
    else:
        tag = f"Today · {deck['name']}"
    card = get_card(cid)
    await msg.edit_text(
        card_front_md(card, tag),
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("Show answer", callback_data=f"show:{cid}")]]))

async def cmd_review(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    if not deck:
        return await update.message.reply_text("Pick a subject first with /deck.")
    due = due_cards(chat, deck["id"], now_ts())
    if not due:
        total = len(deck_cards(chat, deck["id"]))
        return await update.message.reply_text(
            f"All caught up. {total} card{'s' if total != 1 else ''} waiting in the horizon. ✨")
    ctx.user_data["rqueue"] = [c["id"] for c in due]
    await send_next_review(chat, ctx)

async def send_next_review(chat, ctx):
    q = ctx.user_data.get("rqueue", [])
    if not q:
        streak = get_user(chat)["streak"]
        return await ctx.bot.send_message(chat, f"Review done. 🔥 {streak}-day streak.")
    card = get_card(q[0])
    if not card:
        q.pop(0); return await send_next_review(chat, ctx)
    await ctx.bot.send_message(
        chat, card_front_md(card, f"Review · {len(q)} left"),
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("Reveal", callback_data=f"rev:{card['id']}")]]))

async def cmd_quiz(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    if not deck:
        return await update.message.reply_text("Pick a subject first with /deck.")
    cards = deck_cards(chat, deck["id"])
    if not cards:
        return await update.message.reply_text("Nothing to quiz yet — /learn a card first.")
    due = due_cards(chat, deck["id"], now_ts())
    card = random.choice(due if due else cards)
    ctx.user_data["quiz_card"] = card["id"]
    await update.message.reply_text(
        card_front_md(card, "Quiz · type your answer"), parse_mode=ParseMode.HTML)

async def cmd_settime(update: Update, ctx):
    chat = update.effective_chat.id
    ensure_user(chat)
    try:
        h, m = map(int, ctx.args[0].split(":"))
        assert 0 <= h < 24 and 0 <= m < 60
    except Exception:
        return await update.message.reply_text("Use /settime HH:MM, e.g. /settime 07:30")
    with db() as c:
        c.execute("UPDATE users SET digest_h=?, digest_m=? WHERE chat_id=?", (h, m, chat))
    await schedule_digest(ctx.application, chat)
    await update.message.reply_text(
        f"Morning card set for {h:02d}:{m:02d} ({TZ.key}). ☀️")

async def cmd_syllabus(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    if not deck:
        return await update.message.reply_text("Pick a subject first with /deck.")
    topic, done, total = syllabus_progress(deck)
    if not total:
        return await update.message.reply_text(
            f"<b>{deck['name']}</b> doesn't follow a fixed syllabus — daily cards are picked freely "
            f"by the tutor (avoiding repeats).", parse_mode=ParseMode.HTML)
    bar_len = 20
    filled = round(bar_len * done / total)
    bar = "█"*filled + "░"*(bar_len-filled)
    lines = [f"<b>{deck['name']} syllabus</b>", f"<code>{bar}</code> {done}/{total} topics covered", ""]
    if topic:
        lines.append(f"<b>Next up:</b> {topic}")
    else:
        lines.append("<b>Core curriculum complete!</b> Now sending bonus/advanced cards.")
    syl = SYLLABI[deck["syllabus_key"]]
    if done > 0:
        lines.append("")
        lines.append("<i>Recent:</i> " + ", ".join(syl[max(0, done-3):done]))
    await update.message.reply_text("\n".join(lines), parse_mode=ParseMode.HTML)

async def cmd_stats(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    u = get_user(chat)
    if not deck:
        return await update.message.reply_text(f"🔥 {u['streak']}-day streak.\nPick a subject with /deck.")
    cards = deck_cards(chat, deck["id"])
    buckets = [("Due", 0), ("1d", 1.5), ("3d", 4), ("1wk", 9), ("2wk", 20), ("1mo", 45), ("Far", 1e9)]
    counts = [0]*len(buckets)
    for c in cards:
        d = (c["due"] - now_ts())/DAY
        for i, (_, mx) in enumerate(buckets):
            if d <= mx: counts[i] += 1; break
    horizon = "\n".join(f"  {lbl:>4} │ {'●'*n}{'' if n else '·'}  {n or ''}"
                        for (lbl, _), n in zip(buckets, counts))
    await update.message.reply_text(
        f"<b>{deck['name']}</b>\n🔥 {u['streak']}-day streak · {len(cards)} cards\n\n"
        f"<b>Memory horizon</b>\n<code>{horizon}</code>\n\n"
        f"<i>Cards drift right as you get them right.</i>",
        parse_mode=ParseMode.HTML)

async def cmd_cancel(update: Update, ctx):
    ctx.user_data.clear()
    await update.message.reply_text("Cleared. ✦")

async def cmd_usage(update: Update, ctx):
    u = get_usage()
    req, tot = u["requests"], u["total_tokens"]
    pct = min(100, round(100 * req / FREE_RPD_LIMIT)) if FREE_RPD_LIMIT else 0
    bar_len = 20
    filled = round(bar_len * pct / 100)
    bar = "█"*filled + "░"*(bar_len-filled)
    await update.message.reply_text(
        f"<b>Gemini usage today</b> ({today_str()}, {TZ.key})\n\n"
        f"Requests: {req} / {FREE_RPD_LIMIT}\n<code>{bar}</code> {pct}%\n\n"
        f"Tokens — prompt: {u['prompt_tokens']:,} · output: {u['output_tokens']:,} · total: {tot:,}\n\n"
        f"<i>This is a local counter the bot keeps from each API response, not a live read of "
        f"Google's quota — there's no endpoint for that. Free-tier limits can change; check "
        f"aistudio.google.com for the current ceiling on {MODEL}.</i>",
        parse_mode=ParseMode.HTML)

# ── callback queries ──────────────────────────────────────────────────────────
async def on_callback(update: Update, ctx):
    q = update.callback_query
    await q.answer()
    chat = q.message.chat.id
    data = q.data

    if data.startswith("preset:"):
        ensure_user(chat)
        p = PRESETS[int(data.split(":")[1])]
        did = add_deck(chat, p); set_active(chat, did)
        await q.edit_message_text(f"Studying <b>{p['name']}</b>. Pulling your first card…", parse_mode=ParseMode.HTML)
        return await deliver_new_card(chat, ctx)

    if data.startswith("setdeck:"):
        did = int(data.split(":")[1]); set_active(chat, did)
        return await q.edit_message_text(f"Switched to <b>{get_deck(did)['name']}</b>.", parse_mode=ParseMode.HTML)

    if data == "newdeck":
        ctx.user_data["nd"] = {"step": "name"}
        return await ctx.bot.send_message(chat, "New subject — what should I call it? (e.g. <i>Italian verbs</i>)", parse_mode=ParseMode.HTML)

    if data.startswith("ndk:"):
        nd = ctx.user_data.get("nd", {}); nd["kind"] = data.split(":")[1]
        if nd["kind"] == "vocab":
            nd["step"] = "lang"
            return await ctx.bot.send_message(chat, "Which language?")
        nd["step"] = "level"
        return await ctx.bot.send_message(chat, "Level?", reply_markup=level_keyboard())

    if data.startswith("ndl:"):
        nd = ctx.user_data.get("nd", {}); nd["level"] = data.split(":")[1]
        did = add_deck(chat, {"name": nd["name"], "topic": nd["topic"], "level": nd["level"],
                              "kind": nd["kind"], "lang": nd.get("lang")})
        set_active(chat, did); ctx.user_data.pop("nd", None)
        await q.edit_message_text(f"Created <b>{nd['name']}</b>. Pulling your first card…", parse_mode=ParseMode.HTML)
        return await deliver_new_card(chat, ctx)

    if data.startswith("show:"):
        card = get_card(int(data.split(":")[1]))
        return await q.edit_message_text(card_back_md(card), parse_mode=ParseMode.HTML)

    if data.startswith("rev:"):
        card = get_card(int(data.split(":")[1]))
        return await q.edit_message_text(card_back_md(card), parse_mode=ParseMode.HTML,
                                         reply_markup=rate_keyboard(card))

    if data.startswith("rate:"):
        _, cid, rating = data.split(":")
        card = get_card(int(cid))
        if card:
            update_sched(card["id"], schedule(card, rating, now_ts()))
            touch_streak(chat)
        nxt = schedule(card, rating, now_ts())["interval"] if card else 0
        await q.edit_message_text(
            card_back_md(card) + f"\n\n<i>{rating} · next in {preview(card, rating)}</i>",
            parse_mode=ParseMode.HTML)
        qq = ctx.user_data.get("rqueue", [])
        if qq:
            done = qq.pop(0)
            if rating == "again": qq.append(done)   # resurface this session
        return await send_next_review(chat, ctx)

def level_keyboard():
    return InlineKeyboardMarkup([[InlineKeyboardButton(l, callback_data=f"ndl:{l}")
                                  for l in ("beginner", "intermediate", "advanced")]])

# ── free-text handler (custom-deck steps + quiz answers) ──────────────────────
async def on_text(update: Update, ctx):
    chat = update.effective_chat.id
    text = (update.message.text or "").strip()
    nd = ctx.user_data.get("nd")
    if nd:
        if nd["step"] == "name":
            nd["name"] = text; nd["step"] = "topic"
            return await update.message.reply_text("What should I draw cards from? Describe the topic.")
        if nd["step"] == "topic":
            nd["topic"] = text; nd["step"] = "kind"
            kb = InlineKeyboardMarkup([
                [InlineKeyboardButton("Concepts", callback_data="ndk:concept"),
                 InlineKeyboardButton("Terms", callback_data="ndk:term")],
                [InlineKeyboardButton("Vocab", callback_data="ndk:vocab"),
                 InlineKeyboardButton("Deep lesson 📖", callback_data="ndk:lesson")]])
            return await update.message.reply_text(
                "What kind of cards?\n<i>Deep lesson = a few short paragraphs with a worked example "
                "and exam-style takeaway — good for certifications, investing, etc.</i>",
                parse_mode=ParseMode.HTML, reply_markup=kb)
        if nd["step"] == "lang":
            nd["lang"] = text; nd["step"] = "level"
            return await update.message.reply_text("Level?", reply_markup=level_keyboard())
        return

    cid = ctx.user_data.pop("quiz_card", None)
    if cid:
        card = get_card(cid)
        if not card:
            return await update.message.reply_text("That card vanished — try /quiz again.")
        thinking = await update.message.reply_text("Checking…")
        try:
            g = await grade(card, text)
            mark = "✅" if g.get("correct") else "❌"
            rating = "good" if g.get("correct") else "again"
            update_sched(card["id"], schedule(card, rating, now_ts())); touch_streak(chat)
            await thinking.edit_text(
                f"{mark} {g.get('feedback','')}\n\n{card_back_md(card)}\n\n"
                f"<i>scored as {rating} · next in {preview(card, rating)}</i>",
                parse_mode=ParseMode.HTML)
        except Exception as e:
            await thinking.edit_text(f"Couldn't grade that ({e}).\n\n{card_back_md(card)}", parse_mode=ParseMode.HTML)
        return

    await update.message.reply_text("Try /learn, /review, /quiz, or /help.")

# ── morning digest job ────────────────────────────────────────────────────────
async def digest_job(ctx: ContextTypes.DEFAULT_TYPE):
    chat = ctx.job.data
    deck = active_deck(chat)
    if not deck:
        return
    due = len(due_cards(chat, deck["id"], now_ts()))
    greeting = f"☀️ <b>Good morning.</b> Today in <b>{deck['name']}</b>:"
    await ctx.bot.send_message(chat, greeting, parse_mode=ParseMode.HTML)
    if not got_new_today(chat, deck["id"], today_str()):
        await deliver_new_card(chat, ctx)
    if due:
        await ctx.bot.send_message(
            chat, f"You also have {due} card{'s' if due != 1 else ''} due — /review when you're ready.")

async def schedule_digest(app: Application, chat):
    u = get_user(chat)
    if not u:
        return
    for j in app.job_queue.get_jobs_by_name(f"digest:{chat}"):
        j.schedule_removal()
    app.job_queue.run_daily(
        digest_job, time=dt.time(u["digest_h"], u["digest_m"], tzinfo=TZ),
        data=chat, name=f"digest:{chat}")

async def on_startup(app: Application):
    init_db()
    # Defensive: if a webhook was ever set for this token (e.g. by a previous
    # deploy or a different bot framework), polling will conflict with it.
    # Clearing it here is harmless if no webhook is set.
    try:
        await app.bot.delete_webhook(drop_pending_updates=False)
    except Exception as e:
        log.warning("delete_webhook failed (continuing anyway): %s", e)
    for chat in all_user_ids():
        await schedule_digest(app, chat)
    log.info("Daybook ready. Rescheduled digests for %d users.", len(all_user_ids()))

# ── health-check server (for Render's free Web Service tier) ────────────────
class _HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(b"The Daybook is running.")
    def log_message(self, *a, **k):
        pass  # keep request logs out of the main log stream

def start_health_server():
    port = int(os.getenv("PORT", "10000"))
    server = ThreadingHTTPServer(("0.0.0.0", port), _HealthHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    log.info("Health-check server listening on port %d (for Render).", port)

# ── main ──────────────────────────────────────────────────────────────────────
def main():
    token = os.environ["TELEGRAM_BOT_TOKEN"]
    os.environ["GEMINI_API_KEY"]  # fail fast if missing
    app = Application.builder().token(token).post_init(on_startup).build()
    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("help", cmd_help))
    app.add_handler(CommandHandler("learn", cmd_learn))
    app.add_handler(CommandHandler("review", cmd_review))
    app.add_handler(CommandHandler("quiz", cmd_quiz))
    app.add_handler(CommandHandler("deck", cmd_deck))
    app.add_handler(CommandHandler("newdeck", lambda u, c: on_callback_newdeck(u, c)))
    app.add_handler(CommandHandler("stats", cmd_stats))
    app.add_handler(CommandHandler("syllabus", cmd_syllabus))
    app.add_handler(CommandHandler("usage", cmd_usage))
    app.add_handler(CommandHandler("settime", cmd_settime))
    app.add_handler(CommandHandler("cancel", cmd_cancel))
    app.add_handler(CallbackQueryHandler(on_callback))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, on_text))
    start_health_server()
    log.info("Polling…")
    app.run_polling(allowed_updates=Update.ALL_TYPES)

async def on_callback_newdeck(update, ctx):
    ctx.user_data["nd"] = {"step": "name"}
    await update.message.reply_text("New subject — what should I call it? (e.g. <i>Italian verbs</i>)",
                                    parse_mode=ParseMode.HTML)

if __name__ == "__main__":
    main()
