#!/usr/bin/env python3
"""
The Daybook — a "learn one thing a day" Telegram bot.

Each morning it pushes you a fresh flashcard on a subject you're studying,
generated by the Google Gemini API. Older cards resurface on a widening
spaced-repetition schedule (SM-2). You can also review or quiz on demand.

Setup (see the README notes in chat):
  pip install -r requirements.txt
  export TELEGRAM_BOT_TOKEN="123:ABC..."     # from @BotFather
  export GROQ_API_KEY="gsk_..."              # from console.groq.com/keys
  export DAYBOOK_TZ="Asia/Tokyo"             # optional, defaults to UTC
  python daybook_bot.py
"""

import os, sqlite3, time, json, random, asyncio, logging, datetime as dt
from zoneinfo import ZoneInfo
import requests
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.constants import ParseMode
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler, MessageHandler,
    ContextTypes, filters,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("daybook")

MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
TZ    = ZoneInfo(os.getenv("DAYBOOK_TZ", "UTC"))
DB    = os.getenv("DAYBOOK_DB", "daybook.db")
DAY   = 86400.0

PRESETS = [
    {"name": "Japanese words", "topic": "Japanese vocabulary", "level": "beginner",     "kind": "vocab", "lang": "Japanese"},
    {"name": "French words",   "topic": "French vocabulary",   "level": "beginner",     "kind": "vocab", "lang": "French"},
    {"name": "Finance terms",  "topic": "personal finance & investing", "level": "intermediate", "kind": "term"},
    {"name": "Python concepts","topic": "Python programming concepts",  "level": "intermediate", "kind": "concept"},
    {"name": "Big ideas",      "topic": "foundational ideas across science, history & philosophy", "level": "curious", "kind": "concept"},
]

# ── database ─────────────────────────────────────────────────────────────────
def db():
    c = sqlite3.connect(DB)
    c.row_factory = sqlite3.Row
    return c

def init_db():
    with db() as c:
        c.executescript("""
        CREATE TABLE IF NOT EXISTS users(
            chat_id INTEGER PRIMARY KEY, active_deck INTEGER,
            digest_h INTEGER DEFAULT 8, digest_m INTEGER DEFAULT 0,
            streak INTEGER DEFAULT 0, streak_day TEXT);
        CREATE TABLE IF NOT EXISTS decks(
            id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER,
            name TEXT, topic TEXT, level TEXT, kind TEXT, lang TEXT);
        CREATE TABLE IF NOT EXISTS cards(
            id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER, deck_id INTEGER,
            front TEXT, back TEXT, example TEXT, hint TEXT, created REAL,
            interval REAL DEFAULT 0, ease REAL DEFAULT 2.5, reps INTEGER DEFAULT 0,
            lapses INTEGER DEFAULT 0, due REAL, last_reviewed REAL);
        CREATE TABLE IF NOT EXISTS newlog(
            chat_id INTEGER, deck_id INTEGER, last_new TEXT,
            PRIMARY KEY(chat_id, deck_id));
        """)

def ensure_user(chat_id):
    with db() as c:
        c.execute("INSERT OR IGNORE INTO users(chat_id) VALUES(?)", (chat_id,))

def get_user(chat_id):
    with db() as c:
        return c.execute("SELECT * FROM users WHERE chat_id=?", (chat_id,)).fetchone()

def set_active(chat_id, deck_id):
    with db() as c:
        c.execute("UPDATE users SET active_deck=? WHERE chat_id=?", (deck_id, chat_id))

def list_decks(chat_id):
    with db() as c:
        return c.execute("SELECT * FROM decks WHERE chat_id=? ORDER BY id", (chat_id,)).fetchall()

def get_deck(deck_id):
    with db() as c:
        return c.execute("SELECT * FROM decks WHERE id=?", (deck_id,)).fetchone()

def active_deck(chat_id):
    u = get_user(chat_id)
    if not u or not u["active_deck"]:
        return None
    return get_deck(u["active_deck"])

def add_deck(chat_id, d):
    with db() as c:
        cur = c.execute(
            "INSERT INTO decks(chat_id,name,topic,level,kind,lang) VALUES(?,?,?,?,?,?)",
            (chat_id, d["name"], d["topic"], d["level"], d["kind"], d.get("lang")))
        return cur.lastrowid

def deck_cards(chat_id, deck_id):
    with db() as c:
        return c.execute("SELECT * FROM cards WHERE chat_id=? AND deck_id=? ORDER BY id",
                         (chat_id, deck_id)).fetchall()

def due_cards(chat_id, deck_id, now):
    with db() as c:
        return c.execute("SELECT * FROM cards WHERE chat_id=? AND deck_id=? AND due<=? ORDER BY due",
                         (chat_id, deck_id, now)).fetchall()

def get_card(card_id):
    with db() as c:
        return c.execute("SELECT * FROM cards WHERE id=?", (card_id,)).fetchone()

def insert_card(chat_id, deck_id, card, sched, now):
    with db() as c:
        cur = c.execute(
            "INSERT INTO cards(chat_id,deck_id,front,back,example,hint,created,interval,ease,reps,lapses,due,last_reviewed)"
            " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (chat_id, deck_id, card["front"], card["back"], card.get("example",""), card.get("hint",""),
             now, sched["interval"], sched["ease"], sched["reps"], sched["lapses"], sched["due"], now))
        return cur.lastrowid

def update_sched(card_id, s):
    with db() as c:
        c.execute("UPDATE cards SET interval=?,ease=?,reps=?,lapses=?,due=?,last_reviewed=? WHERE id=?",
                  (s["interval"], s["ease"], s["reps"], s["lapses"], s["due"], s["last_reviewed"], card_id))

def mark_new_today(chat_id, deck_id, day):
    with db() as c:
        c.execute("INSERT INTO newlog(chat_id,deck_id,last_new) VALUES(?,?,?) "
                  "ON CONFLICT(chat_id,deck_id) DO UPDATE SET last_new=?", (chat_id, deck_id, day, day))

def got_new_today(chat_id, deck_id, day):
    with db() as c:
        r = c.execute("SELECT last_new FROM newlog WHERE chat_id=? AND deck_id=?", (chat_id, deck_id)).fetchone()
        return bool(r and r["last_new"] == day)

def all_user_ids():
    with db() as c:
        return [r["chat_id"] for r in c.execute("SELECT chat_id FROM users").fetchall()]

# ── time / streak ────────────────────────────────────────────────────────────
def now_ts():
    return time.time()

def today_str():
    return dt.datetime.now(TZ).date().isoformat()

def touch_streak(chat_id):
    u = get_user(chat_id)
    t = today_str()
    if u["streak_day"] == t:
        return u["streak"]
    yest = (dt.datetime.now(TZ).date() - dt.timedelta(days=1)).isoformat()
    new = u["streak"] + 1 if u["streak_day"] == yest else 1
    with db() as c:
        c.execute("UPDATE users SET streak=?, streak_day=? WHERE chat_id=?", (new, t, chat_id))
    return new

# ── spaced repetition (SM-2, lightly tuned) ──────────────────────────────────
def schedule(card, rating, t):
    interval = card["interval"] if card else 0
    ease     = card["ease"] if card else 2.5
    reps     = card["reps"] if card else 0
    lapses   = card["lapses"] if card else 0
    if rating == "again":
        return dict(interval=0, ease=max(1.3, ease-0.2), reps=0, lapses=lapses+1, due=t+60, last_reviewed=t)
    if rating == "hard":
        ease = max(1.3, ease-0.15); interval = 1 if reps == 0 else max(1, round(interval*1.2))
    elif rating == "good":
        interval = 1 if reps == 0 else (3 if reps == 1 else round(interval*ease))
    elif rating == "easy":
        ease += 0.15; interval = 2 if reps == 0 else (4 if reps == 1 else round(interval*ease*1.3))
    return dict(interval=interval, ease=ease, reps=reps+1, lapses=lapses,
                due=t+interval*DAY, last_reviewed=t)

def fmt_days(d):
    if d <= 0: return "now"
    if d < 1:  return f"{round(d*24)}h"
    if d < 30: return f"{round(d)}d"
    if d < 365:return f"{round(d/30)}mo"
    return f"{d/365:.1f}y"

def preview(card, rating):
    return "<10m" if rating == "again" else fmt_days(schedule(card, rating, 0)["interval"])

# ── Groq ──────────────────────────────────────────────────────────────────────
def _groq_sync(system, user, json_out=True):
    key = os.environ["GROQ_API_KEY"]
    url = "https://api.groq.com/openai/v1/chat/completions"
    body = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": 0.9,
    }
    if json_out:
        body["response_format"] = {"type": "json_object"}
    r = requests.post(url, headers={"Content-Type": "application/json",
                                     "Authorization": f"Bearer {key}"},
                      json=body, timeout=40)
    if r.status_code != 200:
        detail = ""
        try: detail = r.json().get("error", {}).get("message", "")
        except Exception: pass
        if r.status_code == 429:
            raise RuntimeError("Hit the Groq free-tier rate limit — try again in a minute.")
        if r.status_code == 401:
            raise RuntimeError("Groq API key was rejected — check GROQ_API_KEY.")
        raise RuntimeError(f"Groq error {r.status_code}: {detail}")
    data = r.json()
    return data["choices"][0]["message"]["content"]

async def groq(system, user, json_out=True):
    return await asyncio.to_thread(_groq_sync, system, user, json_out)

def parse_json(text):
    t = text.replace("```json", "").replace("```", "").strip()
    a, b = t.find("{"), t.rfind("}")
    return json.loads(t[a:b+1] if a >= 0 else t)

async def gen_card(deck, existing_fronts):
    avoid = ("Do NOT repeat any of these already-covered items: "
             + "; ".join(existing_fronts[-40:]) + ".") if existing_fronts else ""
    if deck["kind"] == "vocab":
        lang = deck["lang"]
        shape = (f"front = the {lang} word written naturally "
                 f"(for Japanese, give the word in kanji/kana followed by its reading in parentheses; "
                 f"for French, include the gender article such as le/la/un/une), "
                 f"back = English meaning plus part of speech, "
                 f"example = a natural short sentence in {lang} using the word (add a reading/translation if the script isn't Latin), "
                 f"hint = a brief memory aid.")
    else:
        shape = ("front = the term or concept name, back = a clear 1-2 sentence explanation, "
                 "example = a concrete example or tiny code snippet that makes it click, "
                 "hint = a one-line intuition.")
    system = ("You are a precise, encouraging tutor building ONE spaced-repetition flashcard. "
              "Reply with ONLY a JSON object with keys: front, back, example, hint. Keep each field tight.")
    user = (f"Topic: {deck['topic']}. Level: {deck['level']}. "
            f"Make one genuinely useful, NEW flashcard. {shape} {avoid}")
    return parse_json(await groq(system, user))

async def grade(card, answer):
    system = ('You grade a learner\'s recall attempt generously but honestly. '
              'Reply with ONLY JSON: {"correct": boolean, "feedback": string}. '
              'Feedback is one warm, specific sentence.')
    user = (f'Prompt shown: "{card["front"]}". Expected answer: "{card["back"]}". '
            f'The learner wrote: "{answer}". Was it essentially right?')
    return parse_json(await groq(system, user))

# ── formatting ────────────────────────────────────────────────────────────────
def card_front_md(card, tag=""):
    head = f"<i>{tag}</i>\n" if tag else ""
    hint = f"\n<i>{card['hint']}</i>" if card["hint"] else ""
    return f"{head}<b>{card['front']}</b>{hint}"

def card_back_md(card):
    ex = f"\n\n<code>{card['example']}</code>" if card["example"] else ""
    return f"<b>{card['front']}</b>\n\n{card['back']}{ex}"

def rate_keyboard(card):
    row = [InlineKeyboardButton(f"{r.title()} · {preview(card, r)}", callback_data=f"rate:{card['id']}:{r}")
           for r in ("again", "hard", "good", "easy")]
    return InlineKeyboardMarkup([row[:2], row[2:]])

# ── commands ──────────────────────────────────────────────────────────────────
async def cmd_start(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    chat = update.effective_chat.id
    ensure_user(chat)
    await update.message.reply_text(
        "<b>The Daybook</b> 🌿\nOne thing a day, made to stick.\n\n"
        "Each morning I'll send a fresh card on a subject you're studying, and resurface "
        "older ones right before you'd forget them. Pick a subject to begin:",
        parse_mode=ParseMode.HTML, reply_markup=preset_keyboard())
    await schedule_digest(ctx.application, chat)

def preset_keyboard():
    rows = [[InlineKeyboardButton(p["name"], callback_data=f"preset:{i}")] for i, p in enumerate(PRESETS)]
    rows.append([InlineKeyboardButton("➕ Custom subject", callback_data="newdeck")])
    return InlineKeyboardMarkup(rows)

async def cmd_help(update: Update, ctx):
    await update.message.reply_text(
        "<b>Commands</b>\n"
        "/learn — today's new card\n"
        "/review — go through cards that are due\n"
        "/quiz — get quizzed; type your answer and I'll grade it\n"
        "/deck — switch subject\n"
        "/newdeck — create a custom subject\n"
        "/stats — streak and your memory horizon\n"
        "/settime HH:MM — when to send the morning card\n"
        "/cancel — stop the current action",
        parse_mode=ParseMode.HTML)

async def cmd_deck(update: Update, ctx):
    decks = list_decks(update.effective_chat.id)
    if not decks:
        return await update.message.reply_text("No subjects yet. Use /start to pick one.")
    rows = [[InlineKeyboardButton(d["name"], callback_data=f"setdeck:{d['id']}")] for d in decks]
    rows.append([InlineKeyboardButton("➕ Custom subject", callback_data="newdeck")])
    await update.message.reply_text("Switch subject:", reply_markup=InlineKeyboardMarkup(rows))

async def cmd_learn(update: Update, ctx):
    await deliver_new_card(update.effective_chat.id, ctx)

async def deliver_new_card(chat, ctx, prefix=""):
    deck = active_deck(chat)
    bot = ctx.bot
    if not deck:
        return await bot.send_message(chat, "Pick a subject first with /start or /deck.")
    if got_new_today(chat, deck["id"], today_str()):
        prefix = prefix or "Today's seed is already planted — here's one more anyway.\n\n"
    msg = await bot.send_message(chat, prefix + "✦ Drawing a card…")
    try:
        existing = [c["front"] for c in deck_cards(chat, deck["id"])]
        data = await gen_card(deck, existing)
    except Exception as e:
        return await msg.edit_text(f"Couldn't draw a card: {e}")
    base = {"interval": 0, "ease": 2.5, "reps": 0, "lapses": 0}
    sched = schedule(base, "good", now_ts())          # first sight → returns tomorrow
    cid = insert_card(chat, deck["id"], data, sched, now_ts())
    mark_new_today(chat, deck["id"], today_str())
    touch_streak(chat)
    card = get_card(cid)
    await msg.edit_text(
        card_front_md(card, f"Today · {deck['name']}"),
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("Show answer", callback_data=f"show:{cid}")]]))

async def cmd_review(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    if not deck:
        return await update.message.reply_text("Pick a subject first with /deck.")
    due = due_cards(chat, deck["id"], now_ts())
    if not due:
        total = len(deck_cards(chat, deck["id"]))
        return await update.message.reply_text(
            f"All caught up. {total} card{'s' if total != 1 else ''} waiting in the horizon. ✨")
    ctx.user_data["rqueue"] = [c["id"] for c in due]
    await send_next_review(chat, ctx)

async def send_next_review(chat, ctx):
    q = ctx.user_data.get("rqueue", [])
    if not q:
        streak = get_user(chat)["streak"]
        return await ctx.bot.send_message(chat, f"Review done. 🔥 {streak}-day streak.")
    card = get_card(q[0])
    if not card:
        q.pop(0); return await send_next_review(chat, ctx)
    await ctx.bot.send_message(
        chat, card_front_md(card, f"Review · {len(q)} left"),
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("Reveal", callback_data=f"rev:{card['id']}")]]))

async def cmd_quiz(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    if not deck:
        return await update.message.reply_text("Pick a subject first with /deck.")
    cards = deck_cards(chat, deck["id"])
    if not cards:
        return await update.message.reply_text("Nothing to quiz yet — /learn a card first.")
    due = due_cards(chat, deck["id"], now_ts())
    card = random.choice(due if due else cards)
    ctx.user_data["quiz_card"] = card["id"]
    await update.message.reply_text(
        card_front_md(card, "Quiz · type your answer"), parse_mode=ParseMode.HTML)

async def cmd_settime(update: Update, ctx):
    chat = update.effective_chat.id
    ensure_user(chat)
    try:
        h, m = map(int, ctx.args[0].split(":"))
        assert 0 <= h < 24 and 0 <= m < 60
    except Exception:
        return await update.message.reply_text("Use /settime HH:MM, e.g. /settime 07:30")
    with db() as c:
        c.execute("UPDATE users SET digest_h=?, digest_m=? WHERE chat_id=?", (h, m, chat))
    await schedule_digest(ctx.application, chat)
    await update.message.reply_text(
        f"Morning card set for {h:02d}:{m:02d} ({TZ.key}). ☀️")

async def cmd_stats(update: Update, ctx):
    chat = update.effective_chat.id
    deck = active_deck(chat)
    u = get_user(chat)
    if not deck:
        return await update.message.reply_text(f"🔥 {u['streak']}-day streak.\nPick a subject with /deck.")
    cards = deck_cards(chat, deck["id"])
    buckets = [("Due", 0), ("1d", 1.5), ("3d", 4), ("1wk", 9), ("2wk", 20), ("1mo", 45), ("Far", 1e9)]
    counts = [0]*len(buckets)
    for c in cards:
        d = (c["due"] - now_ts())/DAY
        for i, (_, mx) in enumerate(buckets):
            if d <= mx: counts[i] += 1; break
    horizon = "\n".join(f"  {lbl:>4} │ {'●'*n}{'' if n else '·'}  {n or ''}"
                        for (lbl, _), n in zip(buckets, counts))
    await update.message.reply_text(
        f"<b>{deck['name']}</b>\n🔥 {u['streak']}-day streak · {len(cards)} cards\n\n"
        f"<b>Memory horizon</b>\n<code>{horizon}</code>\n\n"
        f"<i>Cards drift right as you get them right.</i>",
        parse_mode=ParseMode.HTML)

async def cmd_cancel(update: Update, ctx):
    ctx.user_data.clear()
    await update.message.reply_text("Cleared. ✦")

# ── callback queries ──────────────────────────────────────────────────────────
async def on_callback(update: Update, ctx):
    q = update.callback_query
    await q.answer()
    chat = q.message.chat.id
    data = q.data

    if data.startswith("preset:"):
        ensure_user(chat)
        p = PRESETS[int(data.split(":")[1])]
        did = add_deck(chat, p); set_active(chat, did)
        await q.edit_message_text(f"Studying <b>{p['name']}</b>. Pulling your first card…", parse_mode=ParseMode.HTML)
        return await deliver_new_card(chat, ctx)

    if data.startswith("setdeck:"):
        did = int(data.split(":")[1]); set_active(chat, did)
        return await q.edit_message_text(f"Switched to <b>{get_deck(did)['name']}</b>.", parse_mode=ParseMode.HTML)

    if data == "newdeck":
        ctx.user_data["nd"] = {"step": "name"}
        return await ctx.bot.send_message(chat, "New subject — what should I call it? (e.g. <i>Italian verbs</i>)", parse_mode=ParseMode.HTML)

    if data.startswith("ndk:"):
        nd = ctx.user_data.get("nd", {}); nd["kind"] = data.split(":")[1]
        if nd["kind"] == "vocab":
            nd["step"] = "lang"
            return await ctx.bot.send_message(chat, "Which language?")
        nd["step"] = "level"
        return await ctx.bot.send_message(chat, "Level?", reply_markup=level_keyboard())

    if data.startswith("ndl:"):
        nd = ctx.user_data.get("nd", {}); nd["level"] = data.split(":")[1]
        did = add_deck(chat, {"name": nd["name"], "topic": nd["topic"], "level": nd["level"],
                              "kind": nd["kind"], "lang": nd.get("lang")})
        set_active(chat, did); ctx.user_data.pop("nd", None)
        await q.edit_message_text(f"Created <b>{nd['name']}</b>. Pulling your first card…", parse_mode=ParseMode.HTML)
        return await deliver_new_card(chat, ctx)

    if data.startswith("show:"):
        card = get_card(int(data.split(":")[1]))
        return await q.edit_message_text(card_back_md(card), parse_mode=ParseMode.HTML)

    if data.startswith("rev:"):
        card = get_card(int(data.split(":")[1]))
        return await q.edit_message_text(card_back_md(card), parse_mode=ParseMode.HTML,
                                         reply_markup=rate_keyboard(card))

    if data.startswith("rate:"):
        _, cid, rating = data.split(":")
        card = get_card(int(cid))
        if card:
            update_sched(card["id"], schedule(card, rating, now_ts()))
            touch_streak(chat)
        nxt = schedule(card, rating, now_ts())["interval"] if card else 0
        await q.edit_message_text(
            card_back_md(card) + f"\n\n<i>{rating} · next in {preview(card, rating)}</i>",
            parse_mode=ParseMode.HTML)
        qq = ctx.user_data.get("rqueue", [])
        if qq:
            done = qq.pop(0)
            if rating == "again": qq.append(done)   # resurface this session
        return await send_next_review(chat, ctx)

def level_keyboard():
    return InlineKeyboardMarkup([[InlineKeyboardButton(l, callback_data=f"ndl:{l}")
                                  for l in ("beginner", "intermediate", "advanced")]])

# ── free-text handler (custom-deck steps + quiz answers) ──────────────────────
async def on_text(update: Update, ctx):
    chat = update.effective_chat.id
    text = (update.message.text or "").strip()
    nd = ctx.user_data.get("nd")
    if nd:
        if nd["step"] == "name":
            nd["name"] = text; nd["step"] = "topic"
            return await update.message.reply_text("What should I draw cards from? Describe the topic.")
        if nd["step"] == "topic":
            nd["topic"] = text; nd["step"] = "kind"
            kb = InlineKeyboardMarkup([[
                InlineKeyboardButton("Concepts", callback_data="ndk:concept"),
                InlineKeyboardButton("Terms", callback_data="ndk:term"),
                InlineKeyboardButton("Vocab", callback_data="ndk:vocab")]])
            return await update.message.reply_text("What kind of cards?", reply_markup=kb)
        if nd["step"] == "lang":
            nd["lang"] = text; nd["step"] = "level"
            return await update.message.reply_text("Level?", reply_markup=level_keyboard())
        return

    cid = ctx.user_data.pop("quiz_card", None)
    if cid:
        card = get_card(cid)
        if not card:
            return await update.message.reply_text("That card vanished — try /quiz again.")
        thinking = await update.message.reply_text("Checking…")
        try:
            g = await grade(card, text)
            mark = "✅" if g.get("correct") else "❌"
            rating = "good" if g.get("correct") else "again"
            update_sched(card["id"], schedule(card, rating, now_ts())); touch_streak(chat)
            await thinking.edit_text(
                f"{mark} {g.get('feedback','')}\n\n{card_back_md(card)}\n\n"
                f"<i>scored as {rating} · next in {preview(card, rating)}</i>",
                parse_mode=ParseMode.HTML)
        except Exception as e:
            await thinking.edit_text(f"Couldn't grade that ({e}).\n\n{card_back_md(card)}", parse_mode=ParseMode.HTML)
        return

    await update.message.reply_text("Try /learn, /review, /quiz, or /help.")

# ── morning digest job ────────────────────────────────────────────────────────
async def digest_job(ctx: ContextTypes.DEFAULT_TYPE):
    chat = ctx.job.data
    deck = active_deck(chat)
    if not deck:
        return
    due = len(due_cards(chat, deck["id"], now_ts()))
    greeting = f"☀️ <b>Good morning.</b> Today in <b>{deck['name']}</b>:"
    await ctx.bot.send_message(chat, greeting, parse_mode=ParseMode.HTML)
    if not got_new_today(chat, deck["id"], today_str()):
        await deliver_new_card(chat, ctx)
    if due:
        await ctx.bot.send_message(
            chat, f"You also have {due} card{'s' if due != 1 else ''} due — /review when you're ready.")

async def schedule_digest(app: Application, chat):
    u = get_user(chat)
    if not u:
        return
    for j in app.job_queue.get_jobs_by_name(f"digest:{chat}"):
        j.schedule_removal()
    app.job_queue.run_daily(
        digest_job, time=dt.time(u["digest_h"], u["digest_m"], tzinfo=TZ),
        data=chat, name=f"digest:{chat}")

async def on_startup(app: Application):
    init_db()
    for chat in all_user_ids():
        await schedule_digest(app, chat)
    log.info("Daybook ready. Rescheduled digests for %d users.", len(all_user_ids()))

# ── main ──────────────────────────────────────────────────────────────────────
def main():
    token = os.environ["TELEGRAM_BOT_TOKEN"]
    os.environ["GROQ_API_KEY"]  # fail fast if missing
    app = Application.builder().token(token).post_init(on_startup).build()
    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("help", cmd_help))
    app.add_handler(CommandHandler("learn", cmd_learn))
    app.add_handler(CommandHandler("review", cmd_review))
    app.add_handler(CommandHandler("quiz", cmd_quiz))
    app.add_handler(CommandHandler("deck", cmd_deck))
    app.add_handler(CommandHandler("newdeck", lambda u, c: on_callback_newdeck(u, c)))
    app.add_handler(CommandHandler("stats", cmd_stats))
    app.add_handler(CommandHandler("settime", cmd_settime))
    app.add_handler(CommandHandler("cancel", cmd_cancel))
    app.add_handler(CallbackQueryHandler(on_callback))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, on_text))
    log.info("Polling…")
    app.run_polling(allowed_updates=Update.ALL_TYPES)

async def on_callback_newdeck(update, ctx):
    ctx.user_data["nd"] = {"step": "name"}
    await update.message.reply_text("New subject — what should I call it? (e.g. <i>Italian verbs</i>)",
                                    parse_mode=ParseMode.HTML)

if __name__ == "__main__":
    main()
